// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: calendar_service.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqRegister struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqRegister) Reset() {
	*x = ReqRegister{}
	mi := &file_calendar_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqRegister) ProtoMessage() {}

func (x *ReqRegister) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqRegister.ProtoReflect.Descriptor instead.
func (*ReqRegister) Descriptor() ([]byte, []int) {
	return file_calendar_service_proto_rawDescGZIP(), []int{0}
}

func (x *ReqRegister) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ReqRegister) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ReqRegister) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ReqLogin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqLogin) Reset() {
	*x = ReqLogin{}
	mi := &file_calendar_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqLogin) ProtoMessage() {}

func (x *ReqLogin) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqLogin.ProtoReflect.Descriptor instead.
func (*ReqLogin) Descriptor() ([]byte, []int) {
	return file_calendar_service_proto_rawDescGZIP(), []int{1}
}

func (x *ReqLogin) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ReqLogin) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ResLogin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResLogin) Reset() {
	*x = ResLogin{}
	mi := &file_calendar_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResLogin) ProtoMessage() {}

func (x *ResLogin) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResLogin.ProtoReflect.Descriptor instead.
func (*ResLogin) Descriptor() ([]byte, []int) {
	return file_calendar_service_proto_rawDescGZIP(), []int{2}
}

func (x *ResLogin) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type ResUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResUser) Reset() {
	*x = ResUser{}
	mi := &file_calendar_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResUser) ProtoMessage() {}

func (x *ResUser) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResUser.ProtoReflect.Descriptor instead.
func (*ResUser) Descriptor() ([]byte, []int) {
	return file_calendar_service_proto_rawDescGZIP(), []int{3}
}

func (x *ResUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ResUser) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type ReqCreateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	NotifyBefore  *durationpb.Duration   `protobuf:"bytes,5,opt,name=notify_before,json=notifyBefore,proto3" json:"notify_before,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqCreateEvent) Reset() {
	*x = ReqCreateEvent{}
	mi := &file_calendar_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqCreateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqCreateEvent) ProtoMessage() {}

func (x *ReqCreateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqCreateEvent.ProtoReflect.Descriptor instead.
func (*ReqCreateEvent) Descriptor() ([]byte, []int) {
	return file_calendar_service_proto_rawDescGZIP(), []int{4}
}

func (x *ReqCreateEvent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ReqCreateEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ReqCreateEvent) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ReqCreateEvent) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *ReqCreateEvent) GetNotifyBefore() *durationpb.Duration {
	if x != nil {
		return x.NotifyBefore
	}
	return nil
}

type ResCreateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResCreateEvent) Reset() {
	*x = ResCreateEvent{}
	mi := &file_calendar_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResCreateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResCreateEvent) ProtoMessage() {}

func (x *ResCreateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResCreateEvent.ProtoReflect.Descriptor instead.
func (*ResCreateEvent) Descriptor() ([]byte, []int) {
	return file_calendar_service_proto_rawDescGZIP(), []int{5}
}

func (x *ResCreateEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReqGetEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqGetEvent) Reset() {
	*x = ReqGetEvent{}
	mi := &file_calendar_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqGetEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetEvent) ProtoMessage() {}

func (x *ReqGetEvent) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetEvent.ProtoReflect.Descriptor instead.
func (*ReqGetEvent) Descriptor() ([]byte, []int) {
	return file_calendar_service_proto_rawDescGZIP(), []int{6}
}

func (x *ReqGetEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ResEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	NotifyBefore  *durationpb.Duration   `protobuf:"bytes,6,opt,name=notify_before,json=notifyBefore,proto3" json:"notify_before,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResEvent) Reset() {
	*x = ResEvent{}
	mi := &file_calendar_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResEvent) ProtoMessage() {}

func (x *ResEvent) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResEvent.ProtoReflect.Descriptor instead.
func (*ResEvent) Descriptor() ([]byte, []int) {
	return file_calendar_service_proto_rawDescGZIP(), []int{7}
}

func (x *ResEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResEvent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ResEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ResEvent) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ResEvent) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *ResEvent) GetNotifyBefore() *durationpb.Duration {
	if x != nil {
		return x.NotifyBefore
	}
	return nil
}

type ReqListEvents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqListEvents) Reset() {
	*x = ReqListEvents{}
	mi := &file_calendar_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqListEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqListEvents) ProtoMessage() {}

func (x *ReqListEvents) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqListEvents.ProtoReflect.Descriptor instead.
func (*ReqListEvents) Descriptor() ([]byte, []int) {
	return file_calendar_service_proto_rawDescGZIP(), []int{8}
}

func (x *ReqListEvents) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ReqListEvents) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type ResListEvents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*ResEvent            `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResListEvents) Reset() {
	*x = ResListEvents{}
	mi := &file_calendar_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResListEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResListEvents) ProtoMessage() {}

func (x *ResListEvents) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResListEvents.ProtoReflect.Descriptor instead.
func (*ResListEvents) Descriptor() ([]byte, []int) {
	return file_calendar_service_proto_rawDescGZIP(), []int{9}
}

func (x *ResListEvents) GetEvents() []*ResEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type ReqUpdateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	NotifyBefore  *durationpb.Duration   `protobuf:"bytes,6,opt,name=notify_before,json=notifyBefore,proto3" json:"notify_before,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqUpdateEvent) Reset() {
	*x = ReqUpdateEvent{}
	mi := &file_calendar_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqUpdateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUpdateEvent) ProtoMessage() {}

func (x *ReqUpdateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUpdateEvent.ProtoReflect.Descriptor instead.
func (*ReqUpdateEvent) Descriptor() ([]byte, []int) {
	return file_calendar_service_proto_rawDescGZIP(), []int{10}
}

func (x *ReqUpdateEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReqUpdateEvent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ReqUpdateEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ReqUpdateEvent) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ReqUpdateEvent) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *ReqUpdateEvent) GetNotifyBefore() *durationpb.Duration {
	if x != nil {
		return x.NotifyBefore
	}
	return nil
}

type ReqDeleteEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqDeleteEvent) Reset() {
	*x = ReqDeleteEvent{}
	mi := &file_calendar_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqDeleteEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqDeleteEvent) ProtoMessage() {}

func (x *ReqDeleteEvent) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqDeleteEvent.ProtoReflect.Descriptor instead.
func (*ReqDeleteEvent) Descriptor() ([]byte, []int) {
	return file_calendar_service_proto_rawDescGZIP(), []int{11}
}

func (x *ReqDeleteEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_calendar_service_proto protoreflect.FileDescriptor

const file_calendar_service_proto_rawDesc = "" +
	"\n" +
	"\x16calendar_service.proto\x12\bcalendar\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"[\n" +
	"\vReqRegister\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"B\n" +
	"\bReqLogin\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"-\n" +
	"\bResLogin\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"G\n" +
	"\aResUser\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"\xfa\x01\n" +
	"\x0eReqCreateEvent\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12>\n" +
	"\rnotify_before\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\fnotifyBefore\" \n" +
	"\x0eResCreateEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1d\n" +
	"\vReqGetEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x84\x02\n" +
	"\bResEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12>\n" +
	"\rnotify_before\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\fnotifyBefore\"\x81\x01\n" +
	"\rReqListEvents\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\";\n" +
	"\rResListEvents\x12*\n" +
	"\x06events\x18\x01 \x03(\v2\x12.calendar.ResEventR\x06events\"\x8a\x02\n" +
	"\x0eReqUpdateEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12>\n" +
	"\rnotify_before\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\fnotifyBefore\" \n" +
	"\x0eReqDeleteEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\xbf\x04\n" +
	"\x0fCalendarService\x12;\n" +
	"\bRegister\x12\x15.calendar.ReqRegister\x1a\x16.google.protobuf.Empty\"\x00\x121\n" +
	"\x05Login\x12\x12.calendar.ReqLogin\x1a\x12.calendar.ResLogin\"\x00\x126\n" +
	"\aGetUser\x12\x16.google.protobuf.Empty\x1a\x11.calendar.ResUser\"\x00\x12>\n" +
	"\n" +
	"DeleteUser\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12C\n" +
	"\vCreateEvent\x12\x18.calendar.ReqCreateEvent\x1a\x18.calendar.ResCreateEvent\"\x00\x127\n" +
	"\bGetEvent\x12\x15.calendar.ReqGetEvent\x1a\x12.calendar.ResEvent\"\x00\x12@\n" +
	"\n" +
	"ListEvents\x12\x17.calendar.ReqListEvents\x1a\x17.calendar.ResListEvents\"\x00\x12A\n" +
	"\vUpdateEvent\x12\x18.calendar.ReqUpdateEvent\x1a\x16.google.protobuf.Empty\"\x00\x12A\n" +
	"\vDeleteEvent\x12\x18.calendar.ReqDeleteEvent\x1a\x16.google.protobuf.Empty\"\x00B\aZ\x05.;apib\x06proto3"

var (
	file_calendar_service_proto_rawDescOnce sync.Once
	file_calendar_service_proto_rawDescData []byte
)

func file_calendar_service_proto_rawDescGZIP() []byte {
	file_calendar_service_proto_rawDescOnce.Do(func() {
		file_calendar_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_calendar_service_proto_rawDesc), len(file_calendar_service_proto_rawDesc)))
	})
	return file_calendar_service_proto_rawDescData
}

var file_calendar_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_calendar_service_proto_goTypes = []any{
	(*ReqRegister)(nil),           // 0: calendar.ReqRegister
	(*ReqLogin)(nil),              // 1: calendar.ReqLogin
	(*ResLogin)(nil),              // 2: calendar.ResLogin
	(*ResUser)(nil),               // 3: calendar.ResUser
	(*ReqCreateEvent)(nil),        // 4: calendar.ReqCreateEvent
	(*ResCreateEvent)(nil),        // 5: calendar.ResCreateEvent
	(*ReqGetEvent)(nil),           // 6: calendar.ReqGetEvent
	(*ResEvent)(nil),              // 7: calendar.ResEvent
	(*ReqListEvents)(nil),         // 8: calendar.ReqListEvents
	(*ResListEvents)(nil),         // 9: calendar.ResListEvents
	(*ReqUpdateEvent)(nil),        // 10: calendar.ReqUpdateEvent
	(*ReqDeleteEvent)(nil),        // 11: calendar.ReqDeleteEvent
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 13: google.protobuf.Duration
	(*emptypb.Empty)(nil),         // 14: google.protobuf.Empty
}
var file_calendar_service_proto_depIdxs = []int32{
	12, // 0: calendar.ReqCreateEvent.start_time:type_name -> google.protobuf.Timestamp
	12, // 1: calendar.ReqCreateEvent.end_time:type_name -> google.protobuf.Timestamp
	13, // 2: calendar.ReqCreateEvent.notify_before:type_name -> google.protobuf.Duration
	12, // 3: calendar.ResEvent.start_time:type_name -> google.protobuf.Timestamp
	12, // 4: calendar.ResEvent.end_time:type_name -> google.protobuf.Timestamp
	13, // 5: calendar.ResEvent.notify_before:type_name -> google.protobuf.Duration
	12, // 6: calendar.ReqListEvents.start_time:type_name -> google.protobuf.Timestamp
	12, // 7: calendar.ReqListEvents.end_time:type_name -> google.protobuf.Timestamp
	7,  // 8: calendar.ResListEvents.events:type_name -> calendar.ResEvent
	12, // 9: calendar.ReqUpdateEvent.start_time:type_name -> google.protobuf.Timestamp
	12, // 10: calendar.ReqUpdateEvent.end_time:type_name -> google.protobuf.Timestamp
	13, // 11: calendar.ReqUpdateEvent.notify_before:type_name -> google.protobuf.Duration
	0,  // 12: calendar.CalendarService.Register:input_type -> calendar.ReqRegister
	1,  // 13: calendar.CalendarService.Login:input_type -> calendar.ReqLogin
	14, // 14: calendar.CalendarService.GetUser:input_type -> google.protobuf.Empty
	14, // 15: calendar.CalendarService.DeleteUser:input_type -> google.protobuf.Empty
	4,  // 16: calendar.CalendarService.CreateEvent:input_type -> calendar.ReqCreateEvent
	6,  // 17: calendar.CalendarService.GetEvent:input_type -> calendar.ReqGetEvent
	8,  // 18: calendar.CalendarService.ListEvents:input_type -> calendar.ReqListEvents
	10, // 19: calendar.CalendarService.UpdateEvent:input_type -> calendar.ReqUpdateEvent
	11, // 20: calendar.CalendarService.DeleteEvent:input_type -> calendar.ReqDeleteEvent
	14, // 21: calendar.CalendarService.Register:output_type -> google.protobuf.Empty
	2,  // 22: calendar.CalendarService.Login:output_type -> calendar.ResLogin
	3,  // 23: calendar.CalendarService.GetUser:output_type -> calendar.ResUser
	14, // 24: calendar.CalendarService.DeleteUser:output_type -> google.protobuf.Empty
	5,  // 25: calendar.CalendarService.CreateEvent:output_type -> calendar.ResCreateEvent
	7,  // 26: calendar.CalendarService.GetEvent:output_type -> calendar.ResEvent
	9,  // 27: calendar.CalendarService.ListEvents:output_type -> calendar.ResListEvents
	14, // 28: calendar.CalendarService.UpdateEvent:output_type -> google.protobuf.Empty
	14, // 29: calendar.CalendarService.DeleteEvent:output_type -> google.protobuf.Empty
	21, // [21:30] is the sub-list for method output_type
	12, // [12:21] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_calendar_service_proto_init() }
func file_calendar_service_proto_init() {
	if File_calendar_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_calendar_service_proto_rawDesc), len(file_calendar_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calendar_service_proto_goTypes,
		DependencyIndexes: file_calendar_service_proto_depIdxs,
		MessageInfos:      file_calendar_service_proto_msgTypes,
	}.Build()
	File_calendar_service_proto = out.File
	file_calendar_service_proto_goTypes = nil
	file_calendar_service_proto_depIdxs = nil
}
